import type { Calendar, Event, Task } from "./calendar";

export const seedCalendars: Calendar[] = [
  // особисті
  { id: "c1",  name: "Особистий календар Андрія",   ownerType: "user", ownerId: "u1" },
  { id: "c2",  name: "Особистий календар Марії",    ownerType: "user", ownerId: "u2" },
  { id: "c3",  name: "Особистий календар Олега",    ownerType: "user", ownerId: "u3" },
  { id: "c4",  name: "Особистий календар Сергія",   ownerType: "user", ownerId: "u4" },
  { id: "c5",  name: "Особистий календар Катерини", ownerType: "user", ownerId: "u5" },
  { id: "c6",  name: "Особистий календар Дмитра",   ownerType: "user", ownerId: "u6" },
  { id: "c7",  name: "Особистий календар Ірини",    ownerType: "user", ownerId: "u7" },
  { id: "c8",  name: "Особистий календар Юрія",     ownerType: "user", ownerId: "u8" },
  { id: "c9",  name: "Особистий календар Софії",    ownerType: "user", ownerId: "u9" },
  { id: "c10", name: "Особистий календар Владислава", ownerType: "user", ownerId: "u10" },
  { id: "c11", name: "Особистий календар Аліни",    ownerType: "user", ownerId: "u11" },
  { id: "c12", name: "Особистий календар Тараса",   ownerType: "user", ownerId: "u12" },
  { id: "c13", name: "Особистий календар Наталії",  ownerType: "user", ownerId: "u13" },
  { id: "c14", name: "Особистий календар Антона",   ownerType: "user", ownerId: "u14" },
  { id: "c15", name: "Особистий календар Оксани",   ownerType: "user", ownerId: "u15" },

  // командні
  { id: "c16", name: "Командний календар TeamFlow Dev", ownerType: "team", ownerId: "t1" },
  { id: "c17", name: "Командний календар Backend Core", ownerType: "team", ownerId: "t2" },
  { id: "c18", name: "Командний календар Design Squad", ownerType: "team", ownerId: "t3" },
  { id: "c19", name: "Командний календар Marketing Hub", ownerType: "team", ownerId: "t4" },
];


export const seedEvents: Event[] = [
  {
    id: "e1",
    title: "Стратегічна нарада",
    description: "Обговорити план на наступний квартал",
    startDate: new Date("2025-09-14T10:00:00"),
    endDate: new Date("2025-09-14T11:30:00"),
    color: "#FF5733",
    priority: { team: 2, personal: 2 },
    participants: ["u1", "u2"],
    calendarId: "c3",
    ownerId: "u1",
    recurring: { isRecurring: true, periodDays: 7 },
    status: "active",
    tags: ["Meeting"],
    taskIds: ["ta1", "ta2", "ta3", "ta4", "ta5", "ta6", "ta7"] // <-- пов'язуємо з тасками
  },
  {
    id: "e2",
    title: "Code Review Backend",
    description: "Перегляд пул-реквестів для мікросервісів",
    startDate: new Date("2025-09-15T15:00:00"),
    endDate: new Date("2025-09-15T16:00:00"),
    color: "#3498DB",
    priority: { team: 3, personal: 1 },
    participants: ["u2", "u4", "u6", "u12"],
    calendarId: "c17",
    ownerId: "u2",
    recurring: { isRecurring: false, periodDays: 0 },
    status: "active",
    tags: ["Review"],
  },
  {
    id: "e3",
    title: "UI Sync",
    description: "Синхронізація по новому дизайну",
    startDate: new Date("2025-09-16T11:00:00"),
    endDate: new Date("2025-09-16T12:00:00"),
    color: "#9B59B6",
    priority: { team: 2, personal: 1 },
    participants: ["u3", "u5", "u9"],
    calendarId: "c18",
    ownerId: "u3",
    recurring: { isRecurring: true, periodDays: 14 },
    status: "active",
    tags: ["Design"],
  },
  {
    id: "e4",
    title: "1:1 з тімлідом",
    description: "Обговорення прогресу",
    startDate: new Date("2025-09-17T14:00:00"),
    endDate: new Date("2025-09-17T14:30:00"),
    color: "#2ECC71",
    priority: { team: 1, personal: 2 },
    participants: ["u7", "u5"],
    calendarId: "c7",
    ownerId: "u7",
    recurring: { isRecurring: true, periodDays: 30 },
    status: "active",
    tags: ["1:1"],
  },
  {
    id: "e5",
    title: "Стендап",
    description: "Щоденний стендап для команди Dev",
    startDate: new Date("2025-09-14T09:00:00"),
    endDate: new Date("2025-09-14T10:59:00"),
    color: "#E67E22",
    priority: { team: 3, personal: 3 },
    participants: ["u1", "u2", "u3", "u4"],
    calendarId: "c3",
    ownerId: "u1",
    recurring: { isRecurring: true, periodDays: 1 },
    status: "active",
    tags: ["Standup"],
  },
  {
    id: "e6",
    title: "Демо фічі",
    description: "Презентація нової функціональності",
    startDate: new Date("2025-09-18T17:00:00"),
    endDate: new Date("2025-09-18T18:00:00"),
    color: "#1ABC9C",
    priority: { team: 2, personal: 1 },
    participants: ["u6", "u8", "u10", "u14"],
    calendarId: "c17",
    ownerId: "u6",
    recurring: { isRecurring: false, periodDays: 0 },
    status: "active",
    tags: ["Demo"],
  },
  {
    id: "e7",
    title: "Тестування релізу",
    description: "Регресійне тестування перед релізом",
    startDate: new Date("2025-09-19T13:00:00"),
    endDate: new Date("2025-09-19T15:00:00"),
    color: "#C0392B",
    priority: { team: 3, personal: 2 },
    participants: ["u7", "u2", "u12", "u13"],
    calendarId: "c17",
    ownerId: "u7",
    recurring: { isRecurring: false, periodDays: 0 },
    status: "active",
    tags: ["QA"],
  },
  {
    id: "e8",
    title: "Брейншторм маркетингу",
    description: "Ідеї для нової кампанії",
    startDate: new Date("2025-09-20T10:00:00"),
    endDate: new Date("2025-09-20T11:30:00"),
    color: "#F1C40F",
    priority: { team: 2, personal: 1 },
    participants: ["u11", "u5", "u9", "u13"],
    calendarId: "c19",
    ownerId: "u11",
    recurring: { isRecurring: false, periodDays: 0 },
    status: "active",
    tags: ["Marketing"],
  },
  {
    id: "e9",
    title: "Team Building",
    description: "Виїзна подія для всієї команди",
    startDate: new Date("2025-09-21T09:00:00"),
    endDate: new Date("2025-09-21T18:00:00"),
    color: "#16A085",
    priority: { team: 1, personal: 1 },
    participants: ["u1", "u2", "u3", "u4", "u5", "u6", "u7"],
    calendarId: "c16",
    ownerId: "u5",
    recurring: { isRecurring: false, periodDays: 0 },
    status: "active",
    tags: ["Fun"],
  },
  {
    id: "e10",
    title: "Особисте навчання",
    description: "Курс з Kubernetes",
    startDate: new Date("2025-09-22T19:00:00"),
    endDate: new Date("2025-09-22T21:00:00"),
    color: "#34495E",
    priority: { team: 0, personal: 3 },
    participants: ["u4"],
    calendarId: "c4",
    ownerId: "u4",
    recurring: { isRecurring: true, periodDays: 7 },
    status: "active",
    tags: ["Learning"],
  }
];


export const seedTasks: Task[] = [
  // --- Особисті таски ---
  {
    id: "ta1",
    title: "Зробити прототип дизайну",
    description: "Потрібно до понеділка",
    dueDate: new Date("2025-09-14T18:00:00"),
    color: "#33C3FF",
    priority: { team: 2, personal: 1 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u1"],
    type: "personal",
    status: "inProgress",
    calendarId: "c3",
    tags: ["Design", "Frontend"],
  },

  // u1 особисті
  {
    id: "ta2",
    title: "Написати документацію",
    description: "Створити початкову структуру README",
    dueDate: new Date("2025-09-15T12:00:00"),
    color: "#FFAA33",
    priority: { team: 1, personal: 2 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u1"],
    type: "personal",
    status: "notStarted",
    calendarId: "c1",
    tags: ["Docs"],
  },
  {
    id: "ta3",
    title: "Перевірити pull requests",
    description: "Код-рев’ю для u2 та u3",
    dueDate: new Date("2025-09-16T17:00:00"),
    color: "#8E44AD",
    priority: { team: 2, personal: 2 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u1"],
    type: "personal",
    status: "notStarted",
    calendarId: "c1",
    tags: ["CodeReview"],
  },

  // u2 особисті
  {
    id: "ta4",
    title: "Налаштувати CI/CD",
    description: "Використати GitHub Actions",
    dueDate: new Date("2025-09-15T20:00:00"),
    color: "#2ECC71",
    priority: { team: 3, personal: 2 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u2"],
    type: "personal",
    status: "inProgress",
    calendarId: "c2",
    tags: ["DevOps"],
  },
  {
    id: "ta5",
    title: "Зробити тестування API",
    description: "Postman + Jest",
    dueDate: new Date("2025-09-17T14:00:00"),
    color: "#F39C12",
    priority: { team: 2, personal: 3 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u2"],
    type: "personal",
    status: "notStarted",
    calendarId: "c2",
    tags: ["Backend", "Testing"],
  },
  {
    id: "ta6",
    title: "Оновити залежності",
    description: "Перевірити npm пакети",
    dueDate: new Date("2025-09-18T11:00:00"),
    color: "#3498DB",
    priority: { team: 1, personal: 1 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u2"],
    type: "personal",
    status: "notStarted",
    calendarId: "c2",
    tags: ["Maintenance"],
  },

  // u3 особисті
  {
    id: "ta7",
    title: "Оптимізувати SQL-запити",
    description: "Додати індекси в таблиці",
    dueDate: new Date("2025-09-14T19:00:00"),
    color: "#1ABC9C",
    priority: { team: 3, personal: 2 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u3"],
    type: "personal",
    status: "notStarted",
    calendarId: "c3",
    tags: ["Database", "Optimization"],
  },
  {
    id: "ta8",
    title: "Перевірити безпеку JWT",
    description: "Додати refresh токени",
    dueDate: new Date("2025-09-14T09:00:00"),
    color: "#E74C3C",
    priority: { team: 3, personal: 3 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u3"],
    type: "personal",
    status: "inProgress",
    calendarId: "c3",
    tags: ["Security"],
  },
  {
    id: "ta9",
    title: "Виправити баг з календарем",
    description: "Некоректні повторювані події",
    dueDate: new Date("2025-09-14T15:00:00"),
    color: "#9B59B6",
    priority: { team: 2, personal: 2 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u3"],
    type: "personal",
    status: "notStarted",
    calendarId: "c3",
    tags: ["Bugfix"],
  },

  // u4 особисті
  {
    id: "ta10",
    title: "Розробити нову сторінку профілю",
    description: "Аватар, біо, портфоліо",
    dueDate: new Date("2025-09-16T16:00:00"),
    color: "#D35400",
    priority: { team: 2, personal: 2 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u4"],
    type: "personal",
    status: "inProgress",
    calendarId: "c4",
    tags: ["Frontend", "UI"],
  },
  {
    id: "ta11",
    title: "Написати юніт-тести",
    description: "React components",
    dueDate: new Date("2025-09-18T13:00:00"),
    color: "#2C3E50",
    priority: { team: 1, personal: 2 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u4"],
    type: "personal",
    status: "notStarted",
    calendarId: "c4",
    tags: ["Testing"],
  },
  {
    id: "ta12",
    title: "Зробити drag&drop у таск-лісті",
    description: "Реалізувати через React DnD",
    dueDate: new Date("2025-09-20T10:00:00"),
    color: "#27AE60",
    priority: { team: 2, personal: 3 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u4"],
    type: "personal",
    status: "notStarted",
    calendarId: "c4",
    tags: ["Frontend", "Feature"],
  },

  // u5 особисті
  {
    id: "ta13",
    title: "Налаштувати push-нотифікації",
    description: "Web Push API + Service Workers",
    dueDate: new Date("2025-09-15T21:00:00"),
    color: "#C0392B",
    priority: { team: 3, personal: 2 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u5"],
    type: "personal",
    status: "inProgress",
    calendarId: "c5",
    tags: ["Backend", "Notifications"],
  },
  {
    id: "ta14",
    title: "Розробити модуль чату",
    description: "Тільки текстові повідомлення",
    dueDate: new Date("2025-09-17T22:00:00"),
    color: "#16A085",
    priority: { team: 2, personal: 3 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u5"],
    type: "personal",
    status: "inProgress",
    calendarId: "c5",
    tags: ["Chat", "Backend"],
  },
  {
    id: "ta15",
    title: "Оптимізувати WebSocket",
    description: "Зменшити затримки у чаті",
    dueDate: new Date("2025-09-19T18:30:00"),
    color: "#34495E",
    priority: { team: 3, personal: 2 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u5"],
    type: "personal",
    status: "inProgress",
    calendarId: "c5",
    tags: ["Chat", "Optimization"],
  },

  // --- Командні таски ---
  {
    id: "ta16",
    title: "Зробити демо для клієнта",
    description: "Показати основні функції",
    dueDate: new Date("2025-09-21T12:00:00"),
    color: "#2980B9",
    priority: { team: 3, personal: 0 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u1", "u2", "u3"],
    type: "team",
    status: "notStarted",
    calendarId: "c1",
    tags: ["Presentation"],
  },
  {
    id: "ta17",
    title: "Налаштувати деплой на staging",
    description: "AWS EC2",
    dueDate: new Date("2025-09-20T11:00:00"),
    color: "#E67E22",
    priority: { team: 3, personal: 0 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u2", "u4"],
    type: "team",
    status: "inProgress",
    calendarId: "c2",
    tags: ["DevOps"],
  },
  {
    id: "ta18",
    title: "Фіналізувати дизайн системи",
    description: "Узгодити кольори та шрифти",
    dueDate: new Date("2025-09-22T15:00:00"),
    color: "#9B59B6",
    priority: { team: 2, personal: 0 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u1", "u4", "u5"],
    type: "team",
    status: "notStarted",
    calendarId: "c3",
    tags: ["Design"],
  },
  {
    id: "ta19",
    title: "Перевірити інтеграцію з GitHub",
    description: "OAuth + webhooks",
    dueDate: new Date("2025-09-23T19:00:00"),
    color: "#F1C40F",
    priority: { team: 2, personal: 0 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u3", "u5"],
    type: "team",
    status: "notStarted",
    calendarId: "c4",
    tags: ["Integration"],
  },
  {
    id: "ta20",
    title: "Випустити першу alpha-версію",
    description: "Зробити реліз",
    dueDate: new Date("2025-09-25T20:00:00"),
    color: "#27AE60",
    priority: { team: 3, personal: 0 },
    recurring: { isRecurring: false, periodDays: 0 },
    assignedUsers: ["u1", "u2", "u3", "u4", "u5"],
    type: "team",
    status: "notStarted",
    calendarId: "c5",
    tags: ["Release"],
  },
];

