// db/users.seed.ts
import type { User } from "./users";

const now = new Date();

export const seedUsers: User[] = [
  {
    id: "u1",
    username: "andrew",
    fullname: "Андрій Андрусевич",
    email: "andrew@example.com",
    password: "123456",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["frontend", "teamflow", "founder"],
    bio: "Fullstack розробник, люблю TypeScript і C++.",
    skills: ["React", "C++", "Node.js", "PostgreSQL"],
    links: ["https://github.com/andrew", "https://linkedin.com/in/andrew"],
    languages: ["uk", "en"],
    timezone: "Europe/Kyiv",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 30),
    lastActive: now,
    interfaceLang: "uk",
    profileVisibility: "public",
    teams: [],
    plan: "Base",
  },
  {
    id: "u2",
    username: "maria",
    fullname: "Марія Коваленко",
    email: "maria@example.com",
    password: "qwerty",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["backend", "db"],
    bio: "Back-end інженерка, працюю з високонавантаженими системами.",
    skills: ["C++", "Rust", "PostgreSQL"],
    links: ["https://github.com/maria"],
    languages: ["uk", "pl", "en"],
    timezone: "Europe/Warsaw",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 5),
    lastActive: new Date(now.getTime() - 1000 * 60 * 30),
    interfaceLang: "en",
    profileVisibility: "private",
    teams: ["t1", "t2"],
    plan: "Pro",
  },
  {
    id: "u3",
    username: "oleh",
    fullname: "Олег Іваненко",
    email: "oleh@example.com",
    password: "pass123",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["frontend", "ui"],
    bio: "Фронтенд-інженер, люблю дизайн системи.",
    skills: ["React", "Next.js", "CSS", "Figma"],
    links: ["https://dribbble.com/oleh"],
    languages: ["uk", "en"],
    timezone: "Europe/Kyiv",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 10),
    lastActive: now,
    interfaceLang: "uk",
    profileVisibility: "public",
    teams: ["t3"],
    plan: "Base",
  },
  {
    id: "u4",
    username: "sergey",
    fullname: "Сергій Петренко",
    email: "sergey@example.com",
    password: "sergpass",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["devops", "cloud"],
    bio: "DevOps, автоматизація CI/CD процесів.",
    skills: ["Docker", "Kubernetes", "AWS", "Linux"],
    links: ["https://github.com/sergey"],
    languages: ["ru", "uk", "en"],
    timezone: "Europe/Moscow",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 40),
    lastActive: new Date(now.getTime() - 1000 * 60 * 15),
    interfaceLang: "ru",
    profileVisibility: "public",
    teams: ["t2"],
    plan: "Pro",
  },
  {
    id: "u5",
    username: "katya",
    fullname: "Катерина Лисенко",
    email: "katya@example.com",
    password: "password",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["pm", "teamlead"],
    bio: "Проєктна менеджерка, люблю Agile і Kanban.",
    skills: ["Agile", "Scrum", "Jira", "Communication"],
    links: ["https://linkedin.com/in/katya"],
    languages: ["uk", "en", "de"],
    timezone: "Europe/Berlin",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 20),
    lastActive: now,
    interfaceLang: "en",
    profileVisibility: "private",
    teams: ["t4"],
    plan: "Pro",
  },
  {
    id: "u6",
    username: "dmytro",
    fullname: "Дмитро Шевченко",
    email: "dmytro@example.com",
    password: "123qwe",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["ml", "ai"],
    bio: "ML-інженер, працюю з нейромережами.",
    skills: ["Python", "TensorFlow", "PyTorch", "C++"],
    links: ["https://github.com/dmytro"],
    languages: ["uk", "en"],
    timezone: "Europe/Kyiv",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 60),
    lastActive: new Date(now.getTime() - 1000 * 60 * 60),
    interfaceLang: "uk",
    profileVisibility: "public",
    teams: ["t5"],
    plan: "Pro",
  },
  {
    id: "u7",
    username: "iryna",
    fullname: "Ірина Мельник",
    email: "iryna@example.com",
    password: "mypassword",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["qa", "testing"],
    bio: "QA інженерка, люблю автоматизоване тестування.",
    skills: ["Selenium", "Cypress", "Postman"],
    links: ["https://linkedin.com/in/iryna"],
    languages: ["uk", "en", "fr"],
    timezone: "Europe/Paris",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 14),
    lastActive: now,
    interfaceLang: "uk",
    profileVisibility: "private",
    teams: ["t1"],
    plan: "Base",
  },
  {
    id: "u8",
    username: "yurii",
    fullname: "Юрій Бондар",
    email: "yurii@example.com",
    password: "bond007",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["security", "cyber"],
    bio: "Фахівець з кібербезпеки.",
    skills: ["Pentesting", "C++", "Python", "Linux"],
    links: ["https://github.com/yurii"],
    languages: ["uk", "en"],
    timezone: "Europe/London",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 90),
    lastActive: new Date(now.getTime() - 1000 * 60 * 5),
    interfaceLang: "en",
    profileVisibility: "public",
    teams: ["t6"],
    plan: "Enterprise",
  },
  {
    id: "u9",
    username: "sofia",
    fullname: "Софія Дяченко",
    email: "sofia@example.com",
    password: "sofiapass",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["design", "ux"],
    bio: "UI/UX дизайнерка.",
    skills: ["Figma", "Adobe XD", "Illustrator"],
    links: ["https://dribbble.com/sofia"],
    languages: ["uk", "en", "es"],
    timezone: "Europe/Madrid",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 7),
    lastActive: new Date(now.getTime() - 1000 * 60 * 45),
    interfaceLang: "uk",
    profileVisibility: "private",
    teams: [],
    plan: "Base",
  },
  {
    id: "u10",
    username: "vlad",
    fullname: "Владислав Кравчук",
    email: "vlad@example.com",
    password: "kravpass",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["mobile", "ios"],
    bio: "Мобільний розробник під iOS.",
    skills: ["Swift", "Objective-C", "React Native"],
    links: ["https://github.com/vlad"],
    languages: ["uk", "en"],
    timezone: "America/New_York",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 120),
    lastActive: now,
    interfaceLang: "en",
    profileVisibility: "public",
    teams: ["t7"],
    plan: "Pro",
  },
  {
    id: "u11",
    username: "alina",
    fullname: "Аліна Гончар",
    email: "alina@example.com",
    password: "gonchar",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["marketing", "smm"],
    bio: "Маркетолог, спеціалізуюсь на просуванні стартапів.",
    skills: ["SEO", "Google Ads", "Analytics"],
    links: ["https://linkedin.com/in/alina"],
    languages: ["uk", "en", "it"],
    timezone: "Europe/Rome",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3),
    lastActive: new Date(now.getTime() - 1000 * 60 * 10),
    interfaceLang: "uk",
    profileVisibility: "public",
    teams: [],
    plan: "Base",
  },
  {
    id: "u12",
    username: "taras",
    fullname: "Тарас Поліщук",
    email: "taras@example.com",
    password: "taraspass",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["backend", "api"],
    bio: "Back-end розробник, пишу REST та GraphQL API.",
    skills: ["Node.js", "Express", "GraphQL", "C++"],
    links: ["https://github.com/taras"],
    languages: ["uk", "en"],
    timezone: "Europe/Prague",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 25),
    lastActive: new Date(now.getTime() - 1000 * 60 * 60 * 2),
    interfaceLang: "en",
    profileVisibility: "private",
    teams: ["t2", "t5"],
    plan: "Pro",
  },
  {
    id: "u13",
    username: "natalia",
    fullname: "Наталія Савченко",
    email: "natalia@example.com",
    password: "natapass",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["content", "writer"],
    bio: "Контент-мейкерка для блогів і соцмереж.",
    skills: ["Copywriting", "Content Strategy", "Photoshop"],
    links: ["https://linkedin.com/in/natalia"],
    languages: ["uk", "en", "pl"],
    timezone: "Europe/Warsaw",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 50),
    lastActive: new Date(now.getTime() - 1000 * 60 * 20),
    interfaceLang: "uk",
    profileVisibility: "public",
    teams: [],
    plan: "Base",
  },
  {
    id: "u14",
    username: "anton",
    fullname: "Антон Романюк",
    email: "anton@example.com",
    password: "antonpass",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["gamedev", "unity"],
    bio: "Інді-розробник ігор.",
    skills: ["Unity", "C#", "C++", "Blender"],
    links: ["https://github.com/anton"],
    languages: ["uk", "en"],
    timezone: "Europe/Amsterdam",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 200),
    lastActive: now,
    interfaceLang: "en",
    profileVisibility: "private",
    teams: ["t8"],
    plan: "Pro",
  },
  {
    id: "u15",
    username: "oksana",
    fullname: "Оксана Вербицька",
    email: "oksana@example.com",
    password: "oksanapass",
    avatarUrl: "/public/images/fight.jpg",
    tags: ["hr", "recruiter"],
    bio: "HR-спеціалістка, допомагаю збирати команди.",
    skills: ["Recruitment", "Negotiation", "Communication"],
    links: ["https://linkedin.com/in/oksana"],
    languages: ["uk", "en", "de"],
    timezone: "Europe/Vienna",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 12),
    lastActive: new Date(now.getTime() - 1000 * 60 * 55),
    interfaceLang: "uk",
    profileVisibility: "public",
    teams: ["t9"],
    plan: "Base",
  }
];

